// GENERATED by scripts/build-town-manifest.mjs. Do not edit; run `pnpm assets:town`.
// Sizes are read from each GLB in public/town/. Empty means "use the Kenney models".

export type TownKind = 'frontage' | 'tall' | 'backdrop'

export interface TownModel {
  /** path under public/, e.g. town/bld-3-6m-a.glb */
  file: string
  kind: TownKind
  /** width (x), height (y), depth (z) in metres */
  size: [number, number, number]
}

export const TOWN_MODELS: TownModel[] = []
